### ISSUE TITLE
[bug] AttributeError: 'GPTBaseModelConfig' object has no attribute 'dpo_reference_model'

### ISSUE THREAD

**Issue by jlamypoirier** [ServiceNow/Fast-LLM#267]
# 🐞 Describe the Bug

Many tests are failing in main after #223. 

```
FAILED tests/test_checkpoint.py::test_checkpoint_and_eval - AttributeError: 'GPTBaseModelConfig' object has no attribute 'dpo_reference_model'
FAILED tests/test_config.py::test_validate_train_gpt_without_import - RuntimeError: Process failed with return code 1
FAILED tests/test_config.py::test_validate_convert_gpt_without_import - RuntimeError: Process failed with return code 1
FAILED tests/test_config.py::test_validate_example_config - AttributeError: 'GPTBaseModelConfig' object has no attribute 'dpo_reference_model'
FAILED tests/test_mb.py::test_model_df4 - AttributeError: 'GPTBaseModelConfig' object has no attribute 'dpo_reference_model'
FAILED tests/test_mb_seq_first.py::test_model_df4_sf - AttributeError: 'GPTBaseModelConfig' object has no attribute 'dpo_reference_model'
FAILED tests/test_ms.py::test_model_ms256 - AttributeError: 'GPTBaseModelConfig' object has no attribute 'dpo_reference_model'
FAILED tests/test_mtp.py::test_transformer_mtp[config_dict0] - AttributeError: 'GPTBaseModelConfig' object has no attribute 'enable_dpo'
FAILED tests/test_mtp.py::test_transformer_mtp[config_dict1] - AttributeError: 'GPTBaseModelConfig' object has no attribute 'enable_dpo'
FAILED tests/test_mtp.py::test_transformer_mtp[config_dict2] - AttributeError: 'GPTBaseModelConfig' object has no attribute 'enable_dpo'
FAILED tests/test_multi_stage.py::test_frozen_weights - AttributeError: 'GPTBaseModelConfig' object has no attribute 'dpo_reference_model'
FAILED tests/test_seq_first.py::test_model_sf - AttributeError: 'GPTBaseModelConfig' object has no attribute 'dpo_reference_model'
FAILED tests/test_simple.py::test_model_safe - AttributeError: 'GPTBaseModelConfig' object has no attribute **'dpo_reference_model'**
```

@tobyzl2 Can you please have a look?

**Comment by jlamypoirier** [comment]
Issue was on my side
