### PR TITLE
Declarative weight conversion framework

### PR DESCRIPTION
**Pull request by jlamypoirier**
## Summary

Mirrors the post-#508 declarative config-side shape on the weight side. Every section converter now declares its weight mapping via ``_create_weight_converters`` (cached, override-by-key), the walker flattens into the existing ``list[WeightConverter]`` runtime, and tied embeddings move from per-call ``drop_on_export=tied`` plumbing into the walker-central ``OutputProjectionWeightConverter`` marker. Item 1 of the post-#508 deferred list.

## What changed

* **Framework in ``external.py``** — new primitives ``NestedWeightConverter``, three block-sequence variants (``BlockSequenceWeightConverter`` for attribute-reached sequences, ``DispatchBlockSequenceWeightConverter`` for per-position type dispatch via a registry on ``type(block.mixer)``, ``SelfBlockSequenceWeightConverter`` for when the section config IS the sequence), ``DispatchWeightConverter`` (single-attribute type dispatch), ``TypedDictWeightConverter`` (per-key dispatch on ``dict[str, Config]``), ``LinearWeightConverter`` (bundles ``.weight``/``.bias`` with per-section ``bias_fn``), ``OutputProjectionWeightConverter`` (walker-dropped when ``root_config.tied_embedding_weight`` is set). Generic transforms ``KeyValueWeightConverter`` / ``TransposeSplitWeightConverter`` (was ``MLPLayer2Converter``) / ``PatchEmbeddingWeightConverter`` relocate here from llama.py / llava.py.
* **All formats migrated** — llama, mistral, qwen2, mixtral, mtp_llama, gemma4, diffusion_dream, diffusion_llama, apriel, apriel2, llava, apriel2-multimodal.
* **Cleanup** — ``get_parameter_converter``, ``get_weight_and_bias_converters``, ``MLPLayer2Converter`` alias, and the ``drop_on_export`` parameter plumbing are removed. ``effective_bias`` stays as a published helper for Apriel/Apriel2 ``CustomConfigConverter`` export_fns.

## Test plan

- [x] tests/models/{test_converters,test_checkpoint,test_hf_roundtrip}.py — **281 passed** (cluster, 8 workers, 72s). Matches post-#508 baseline.
- [x] Full tests/models/ suite — **409 passed, 259 skipped** (local).
- [x] fast_llm_external_models/tests/ — **2109 passed, 42 skipped** (cluster). Matches post-#508 baseline.

## Follow-up

* Extending the static converter test walker to weight coverage (every state-dict key emitted by a default-constructed model is consumed by some leaf ``WeightConverter``) is worth doing but not on the critical path — deferred.
* ``LlamaBaseModelConverter._create_weight_converters`` returns ``embeddings`` + ``decoder`` but the head still appends imperatively in ``get_converters`` because the MTP-Llama head needs the full base-model config (for per-prediction-head fan-out). Extracting an MTP-specific section converter so the standard head can sit in the declarative dict is a clean follow-up; out of scope here.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by jlamypoirier** [comment]
## CI status [fixed as of #524]

CI shows **60 failures**, but these are pre-existing and identical to main's. Confirmed by diffing the failed-test names: `cmp /tmp/main_failed /tmp/pr_failed` → identical.

All failures are `TypeError: create_causal_mask() got an unexpected keyword argument 'cache_position'` from `fast_llm_external_models/apriel2/modeling_apriel2.py:940` — a transformers-version mismatch introduced by #521 (PyTorch base image bump to 26.02-py3 brought a newer transformers where `create_causal_mask` dropped the `cache_position` kwarg). None of these files are touched by this PR.

Local + cluster results on the PR's HEAD:

- `tests/models/{test_converters,test_checkpoint,test_hf_roundtrip}.py` (cluster, 8 workers): **281 passed** — matches post-#508 baseline.
- Full `tests/models/` (local): **409 passed, 259 skipped**.
- `fast_llm_external_models/tests/` (cluster, image without the transformers bump): **2109 passed, 42 skipped** — matches post-#508 baseline.
